# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jeffrey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 5.15'
  pod 'Alamofire', '~> 5.4'
  pod 'TextFieldEffects'
  pod 'SnapKit', '~> 5.0.0'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'

  # Pods for Jeffrey

  target 'JeffreyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JeffreyUITests' do
    # Pods for testing
  end

end
